package model

type Profile struct {
	// 姓名
	Name string
	// 年龄
	Age int
	// 头像url
	AvatarURL string
	// 基本信息
	BasicInfo []string
	// 详细信息
	DetailInfo []string
	// 教育程度
	Education string
	// 性别
	Gender int
	// 性别名称
	GenderString string
	//是否有个人介绍
	HasIntroduce bool
	// 身高
	HeightString string
	// 内心独白
	IntroduceContent string
	// 是否会员
	IsStar string
	// 最新上线时间
	LastLoginTimeString string
	// 婚姻状态
	MarriageString string
	// 别名
	Nickname string
	// 对象年龄
	ObjectAgeString string
	// 对象身体
	ObjectBodyString string
	// 对象孩子
	ObjectChildrenString string
	// 对象教育
	ObjectEducationString string
	// 对象身高
	ObjectHeightString string
	// 对象信息
	ObjectInfo []string
	// 对象婚姻
	ObjectMarriageString string
	// 对象工资
	ObjectSalaryString string
	// 是否想要孩子
	ObjectWantChildrenString string
	// 对象工作地点
	ObjectWorkCityString string
	// 照片数量
	PhotoCount int
	// 照片信息
	Photos []PictureInfo
	// 工资
	SalaryString string
	// 工作城市
	WorkCityString string
	// 工作地
	WorkProvinceCityString string
	// 兴趣
	Interest []Interest
}
